### ISSUE TITLE
repeat command produce incorrect results

### ISSUE THREAD

**Issue by ghostbuster91** [ghostbuster91/nvim-next#12]
tested using `d]M` + dot repeat

**Comment by Hubro** [comment]
I was just about to report this. I use `df.`, `dt ` etc. commands a lot, and I'm unable to repeat them.

**Comment by ghostbuster91** [comment]
motions as `d]M` are now repeatable and they produce correct results. 
Lack of ability to repaet `f`/`t` motions is a different issue - https://github.com/ghostbuster91/nvim-next/issues/14
