### ISSUE TITLE
Feature Request: sibling-swap.nvim integration

### ISSUE THREAD

**Issue by kevintraver** [ghostbuster91/nvim-next#21]
It would be awesome to have sibling-swap.nvim integration.

**Comment by ghostbuster91** [comment]
I don't see any movements defined there, only the swap action. If so, I would suggest using something like `dot-repeat` for making it repeatable as dot is by convention used to repeat actions. 

But maybe I have missed something, can you tell what would you like this integration to have?

**Comment by kevintraver** [comment]
Thank you for the explanation! I'll actually go ahead and close this.
